dist: xenial
language: cpp

services:
- docker

install:
- docker pull dkormalev/asynqro-builder:latest;

jobs:
  include:
  - &main
    name: Compilation & tests (Release, clang 7)
    compiler: clang
    script:
    - docker run --rm -v $(pwd):/asynqro -e "CXX=clang++" -e "CC=clang" dkormalev/asynqro-builder Release
  - <<: *main
    name: Compilation & tests (Release, gcc 8)
    compiler: gcc
    script:
    - docker run --rm -v $(pwd):/asynqro -e "CXX=g++" -e "CC=gcc" dkormalev/asynqro-builder Release
  - <<: *main
    name: Code coverage calculation (Debug, gcc 8)
    compiler: gcc
    script:
    - docker run --rm -v $(pwd):/asynqro -e "CXX=g++" -e "CC=gcc" --entrypoint=/codecov.sh dkormalev/asynqro-builder
    after_success:
    - bash <(curl -s https://codecov.io/bash) -s code_coverage
#    - bash <(curl -s https://codecov.io/bash) -f coverage.info
