dist: xenial
language: cpp

services:
- docker

install:
- docker pull dkormalev/asynqro-builder:latest

jobs:
  include:
  - &main
    name: Compilation & tests (Release, clang 7, qt5)
    compiler: clang
    script:
    - docker run --rm -v $(pwd):/asynqro -e "CXX=clang++" -e "CC=clang" dkormalev/asynqro-builder Release
  - <<: *main
    name: Compilation & tests (Release, gcc 8, qt5)
    compiler: gcc
    script:
    - docker run --rm -v $(pwd):/asynqro -e "CXX=g++" -e "CC=gcc" dkormalev/asynqro-builder Release
  - <<: *main
    name: Compilation & tests (Release, clang 7, no qt)
    compiler: clang
    script:
    - docker run --rm -v $(pwd):/asynqro -e "CXX=clang++" -e "CC=clang" --entrypoint=/build_noqt.sh dkormalev/asynqro-builder Release
  - <<: *main
    name: Compilation & tests (Release, gcc 8, no qt)
    compiler: gcc
    script:
    - docker run --rm -v $(pwd):/asynqro -e "CXX=g++" -e "CC=gcc" --entrypoint=/build_noqt.sh dkormalev/asynqro-builder Release
  - <<: *main
    name: Code coverage calculation (Debug, gcc 8, qt5, lcov, codecov.io)
    compiler: gcc
    if: type == pull_request OR branch == master OR branch == develop
    script:
    - docker run --rm -v $(pwd):/asynqro -e "CXX=g++" -e "CC=gcc" --entrypoint=/codecov.sh dkormalev/asynqro-builder
    after_success:
    - bash <(curl -s https://codecov.io/bash) -f code_coverage.total
